### ISSUE TITLE
Handle paged results

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/latest-commit#1]
In the case a commit can't be found on the first result page.

Use the `Link` header you get from GitHub:

```
Link <https://api.github.com/user/1913805/events?page=2>; rel="next" <https://api.github.com/user/1913805/events?page=10>; rel="last"
```

Should probably set a default max at 5 pages and let it be configurable.

**Comment by SamVerschueren** [comment]
Is it necessary to parse the `Link` header? What if I use a `page` variable that is incremented every time a page was retrieved. Looks easier to me.

**Comment by sindresorhus** [comment]
The Link header is the right way to do it. There's probably a module on npm for parsing it. If you don't you'll end up with one moot request when there are no more pages, or even when there are only one page.

**Comment by SamVerschueren** [comment]
Using `latest-push` now which handles the paging.
